### ISSUE TITLE
Output still seems to be detected as having Multiple Vertexes

### ISSUE THREAD

**Issue by Arganom** [eArmada8/vbuffer_merge_split#3]
Using this script still produces the error message of "only supports single Vertex" when trying to import into Blender, I've submitted the files that I've had merged as well as the output folder from a game called Ghost Recon Future Soldier. Can you possibly tell if there's anything off on how my Captures are being produced/outputted? 

I've also included the 2 pictures of the model i'm working with as the first two files in the zip file..... and the part of the model I'm trying to select and import into blender with Frame analysis.

[GRFS dx11  FrameAnalysis-2022-11-27-164554.zip](https://github.com/eArmada8/vbuffer_merge_split/files/10099268/GRFS.dx11.FrameAnalysis-2022-11-27-164554.zip)

**Comment by Arganom** [comment]
Hi again, Just wanted to ask if there might be any interest in checking my inquiry.

**Comment by eArmada8** [comment]
Hi, the frame analysis you uploaded does not have multiple vertex buffers.  My script will not be able to help you, since it is written for merging and splitting multiple buffers.  You can tell if there are multiple buffers if there are multiple vb files per ib (.vb0, .vb1, .vb2, etc...) - your dump only has .vb0 for every .ib however.

I took a look at your frame dump, and there are invalid values; for example in 000061-vb0.txt:

vb0[1580]+000 POSITION: 19681, -76, 32767, 22104
vb0[1580]+024 NORMAL: 0.788628817, -0.00585955381, 0.60860014, 0
vb0[1580]+008 TEXCOORD: 190, 50, -1, -1
vb0[1580]+032 TANGENT: 0.0156254768, -0.497054964, -0.0273751039, 0
vb0[1580]+016 BLENDWEIGHT: 0.827450991, 0.172549024, 0, 0
vb0[1580]+020 BLENDINDICES: 8, 4, 0, 0
vb0[1580]+000 COLOR: -1.#QNAN

You can see the color value is not a number.  You can try importing the raw buffers instead; when importing check the "Load .buf files instead" option.  I was able to successfully load your frame dump when I checked that option, however it does not appear that any of the meshes that you provided are useable.  (They will load successfully, but I don't see the model.)

You may want to ask the developers of 3DMigoto, or the developer of the import plugin.  My script does not apply here though, since it is for merging.  I'm going to close this issue for now.

**Comment by Arganom** [comment]
Thanks Armada, This was VERY educational, and will help me in the future.
