### ISSUE TITLE
Vertex Groups for weights not shown - OPUWR

### ISSUE THREAD

**Issue by HazzyDevil** [eArmada8/vbuffer_merge_split#6]
Hello again,

I just tested your script in one piece unlimited world red. Imports into blender, I can edit and then export, use your script again to split buffers and then see the mod in game.

However, there doesn't appear to be any vertex groups when importing into blender, as a result mod in-game is all distorted 

![image](https://user-images.githubusercontent.com/28854701/209318367-7dbaef5f-feac-4fd0-9ca7-b06568e2b393.png)

**Comment by eArmada8** [comment]
While I don't have this game to test, I have seen this issue before.  This isn't an issue with my script, it is an issue with the game engine itself.  There are games where the GPU isn't animating the models (at least in the draw call that 3DMigoto is analyzing).  You can tell in your screenshot as the mesh is already posed; it is not in the bind pose.

See here: https://github.com/bo3b/3Dmigoto/issues/165

My conclusion is that 3DMigoto cannot mod this game, at least not as currently written.

**Comment by HazzyDevil** [comment]
Hey thanks for getting back to me! I spoke with SilentNightSound and it appears the game is doing two things that needs to be addressed but is doable.

The first issue is instead of having elements being called BLENDWEIGHTS and BLENDINDICIES, the engine calls them WEIGHT_VALUE and WEIGHT_INDEX. No biggie, just an easy find and replace in the vb0 file.

The other issue is that WEIGHT_INDEX data is in the format of R32_UINT whereas WEIGHT_VALUES is in R32G32B32A32_FLOAT. So there’s 4 vertex but there are only 1 indicie. So the R32_UINT needs to be converted to to R8G8B8A8_UINT that way each vertex has a corresponding indicie.

**Comment by eArmada8** [comment]
Glad to hear you sorted it out! If you want to see what happens when you reinterpret 32 bits as one format instead of another, you have a few options. First though, add "buf" to the dump options so you have access to the raw buffers. The fastest option is to use a hex editor like HxD, which lets you see how byte will be interpreted. The second option is using the Blender plug-in directly, it has an option that lets you import the buf files instead of the txt files but you will have to merge them first.
